export const types = {
	SEND_MESSAGE: 'SEND_MESSAGE',
	
	LOGIN_REQUEST:'LOGIN_REQUEST',
	LOGIN_FAILURE:'LOGIN_FAILURE',
	LOGIN_SUCCESS:'LOGIN_SUCCESS',
	LOGOUT_SUCCESS:'LOGOUT_SUCCESS',

	SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
	SIGNUP_FAILURE:'SIGNUP_FAILURE'
};