export const types = {
	SEND_MESSAGE: 'SEND_MESSAGE',
	
	LOGIN_REQUEST:'LOGIN_REQUEST',
	LOGIN_FAILURE:'LOGIN_FAILURE',
	LOGIN_SUCCESS:'LOGIN_SUCCESS',
	LOGOUT_SUCCESS:'LOGOUT_SUCCESS',

	SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
	SIGNUP_FAILURE:'SIGNUP_FAILURE',
	ADD_USER: 'ADD_USER',
	USER_LEFT_CHAT: 'USER_LEFT_CHAT',
	GET_ACTIVE_USERS_REQUEST: 'GET_ACTIVE_USERS_REQUEST',
	GET_ACTIVE_USERS_SUCCESS: 'GET_ACTIVE_USERS_SUCCESS',
	GET_ACTIVE_USERS_FAILURE: 'GET_ACTIVE_USERS_FAILURE',
	SET_CURRENT_USER_TO_NULL: 'SET_CURRENT_USER_TO_NULL',
	GET_SOCKET: 'GET_SOCKET',
	TYPING: 'TYPING',
	STOP_TYPING: 'STOP_TYPING',
	NOT_ACTIVE_USERS: 'NOT_ACTIVE_USERS'
};